Authorization.create(description:"Uso de imagem")
Authorization.create(description:"Passeios e Eventos")
Authorization.create(description:"Retirar livros na biblioteca")
AdditionalActivity.create(activity:"Mais Educação")
AdditionalActivity.create(activity:"Sala de Recursos")
AdditionalActivity.create(activity:"Laboratório de Aprendizagem")
AdditionalActivity.create(activity:"Reforço Escolar")